
package com.ifli.mbcp.service.remote;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://www.CDCCRM.com/webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param serviceRequestId
     * @param createServiceRequestResult
     * @param errorDetails
     * @param attachments
     * @param serviceRequest
     * @param channel
     * @param user
     */
    @WebMethod(operationName = "CreateServiceRequest", action = "http://www.CDCCRM.com/webservices/CreateServiceRequest")
    @RequestWrapper(localName = "CreateServiceRequest", targetNamespace = "http://www.CDCCRM.com/webservices/", className = "com.ifli.mbcp.service.remote.CreateServiceRequest")
    @ResponseWrapper(localName = "CreateServiceRequestResponse", targetNamespace = "http://www.CDCCRM.com/webservices/", className = "com.ifli.mbcp.service.remote.CreateServiceRequestResponse")
    public void createServiceRequest(
        @WebParam(name = "User", targetNamespace = "http://www.CDCCRM.com/webservices/")
        User user,
        @WebParam(name = "Channel", targetNamespace = "http://www.CDCCRM.com/webservices/")
        String channel,
        @WebParam(name = "serviceRequest", targetNamespace = "http://www.CDCCRM.com/webservices/")
        CreateServiceRequest2 serviceRequest,
        @WebParam(name = "attachments", targetNamespace = "http://www.CDCCRM.com/webservices/")
        ArrayOfAttachment attachments,
        @WebParam(name = "CreateServiceRequestResult", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<Boolean> createServiceRequestResult,
        @WebParam(name = "ErrorDetails", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfError> errorDetails,
        @WebParam(name = "ServiceRequestId", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<String> serviceRequestId);

    /**
     * 
     * @param serviceRequestId
     * @param addNotes
     * @param errorDetails
     * @param serviceRequest
     * @param closeServiceRequestResult
     * @param channel
     * @param user
     */
    @WebMethod(operationName = "CloseServiceRequest", action = "http://www.CDCCRM.com/webservices/CloseServiceRequest")
    @RequestWrapper(localName = "CloseServiceRequest", targetNamespace = "http://www.CDCCRM.com/webservices/", className = "com.ifli.mbcp.service.remote.CloseServiceRequest")
    @ResponseWrapper(localName = "CloseServiceRequestResponse", targetNamespace = "http://www.CDCCRM.com/webservices/", className = "com.ifli.mbcp.service.remote.CloseServiceRequestResponse")
    public void closeServiceRequest(
        @WebParam(name = "User", targetNamespace = "http://www.CDCCRM.com/webservices/")
        User user,
        @WebParam(name = "Channel", targetNamespace = "http://www.CDCCRM.com/webservices/")
        String channel,
        @WebParam(name = "AddNotes", targetNamespace = "http://www.CDCCRM.com/webservices/")
        boolean addNotes,
        @WebParam(name = "serviceRequest", targetNamespace = "http://www.CDCCRM.com/webservices/")
        CloseServiceRequest2 serviceRequest,
        @WebParam(name = "CloseServiceRequestResult", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<Boolean> closeServiceRequestResult,
        @WebParam(name = "ErrorDetails", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfError> errorDetails,
        @WebParam(name = "ServiceRequestId", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<String> serviceRequestId);

    /**
     * 
     * @param serviceRequestId
     * @param errorDetails
     * @param applicationNumber
     * @param serviceRequestDetails
     * @param policyNumber
     * @param customerID
     * @param viewServiceRequestResult
     * @param channel
     * @param user
     */
    @WebMethod(operationName = "ViewServiceRequest", action = "http://www.CDCCRM.com/webservices/ViewServiceRequest")
    @RequestWrapper(localName = "ViewServiceRequest", targetNamespace = "http://www.CDCCRM.com/webservices/", className = "com.ifli.mbcp.service.remote.ViewServiceRequest")
    @ResponseWrapper(localName = "ViewServiceRequestResponse", targetNamespace = "http://www.CDCCRM.com/webservices/", className = "com.ifli.mbcp.service.remote.ViewServiceRequestResponse")
    public void viewServiceRequest(
        @WebParam(name = "User", targetNamespace = "http://www.CDCCRM.com/webservices/")
        User user,
        @WebParam(name = "Channel", targetNamespace = "http://www.CDCCRM.com/webservices/")
        String channel,
        @WebParam(name = "CustomerID", targetNamespace = "http://www.CDCCRM.com/webservices/")
        long customerID,
        @WebParam(name = "PolicyNumber", targetNamespace = "http://www.CDCCRM.com/webservices/")
        long policyNumber,
        @WebParam(name = "ApplicationNumber", targetNamespace = "http://www.CDCCRM.com/webservices/")
        long applicationNumber,
        @WebParam(name = "ServiceRequestId", targetNamespace = "http://www.CDCCRM.com/webservices/")
        long serviceRequestId,
        @WebParam(name = "ViewServiceRequestResult", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<Boolean> viewServiceRequestResult,
        @WebParam(name = "ErrorDetails", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfError> errorDetails,
        @WebParam(name = "ServiceRequestDetails", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfServiceRequest> serviceRequestDetails);

    /**
     * 
     * @param serviceRequestId
     * @param createSRClaimsAccApprovalResult
     * @param errorDetails
     * @param policyNumber
     * @param claimNumber
     * @param channel
     * @param user
     * @param claimSeqNo
     */
    @WebMethod(operationName = "CreateSRClaimsAccApproval", action = "http://www.CDCCRM.com/webservices/CreateSRClaimsAccApproval")
    @RequestWrapper(localName = "CreateSRClaimsAccApproval", targetNamespace = "http://www.CDCCRM.com/webservices/", className = "com.ifli.mbcp.service.remote.CreateSRClaimsAccApproval")
    @ResponseWrapper(localName = "CreateSRClaimsAccApprovalResponse", targetNamespace = "http://www.CDCCRM.com/webservices/", className = "com.ifli.mbcp.service.remote.CreateSRClaimsAccApprovalResponse")
    public void createSRClaimsAccApproval(
        @WebParam(name = "User", targetNamespace = "http://www.CDCCRM.com/webservices/")
        User user,
        @WebParam(name = "Channel", targetNamespace = "http://www.CDCCRM.com/webservices/")
        String channel,
        @WebParam(name = "PolicyNumber", targetNamespace = "http://www.CDCCRM.com/webservices/")
        String policyNumber,
        @WebParam(name = "ClaimNumber", targetNamespace = "http://www.CDCCRM.com/webservices/")
        String claimNumber,
        @WebParam(name = "ClaimSeqNo", targetNamespace = "http://www.CDCCRM.com/webservices/")
        String claimSeqNo,
        @WebParam(name = "CreateSRClaimsAccApprovalResult", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<Boolean> createSRClaimsAccApprovalResult,
        @WebParam(name = "ErrorDetails", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfError> errorDetails,
        @WebParam(name = "ServiceRequestId", targetNamespace = "http://www.CDCCRM.com/webservices/", mode = WebParam.Mode.OUT)
        Holder<String> serviceRequestId);

}
